name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Show release outputs
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "A release was created."
          echo "Tag: ${{ steps.release.outputs.tag_name }}"
          echo "SHA: ${{ steps.release.outputs.sha }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
